# Generated by Django 5.2.5 on 2025-09-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='datetime',
            new_name='date',
        ),
    ]
