# Generated by Django 5.2.6 on 2025-09-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='sala_reserved',
            new_name='room_reserved',
        ),
    ]
