# Generated by Django 5.2.5 on 2025-09-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
        ('reserves', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='sala_reserved',
        ),
        migrations.AddField(
            model_name='schedules',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_created', to='authent.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='room_reserved',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_schedules', to='rooms.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
