# Generated by Django 5.2.5 on 2025-09-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
        ('reserves', '0002_rename_sala_reserved_schedules_room_reserved'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='datetime',
        ),
        migrations.AddField(
            model_name='schedules',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_created', to='authent.users'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='room_reserved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_schedules', to='rooms.room'),
        ),
    ]
