# Generated by Django 5.2.5 on 2025-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0003_remove_schedules_datetime_schedules_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
