# Generated by Django 5.2.5 on 2025-09-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
        ('reserves', '0004_alter_schedules_start_time'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_created', to='authent.users'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='room_reserved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_schedules', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
