# Generated by Django 5.2.5 on 2025-09-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
        ('reserves', '0005_alter_schedules_created_by_alter_schedules_end_time_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_created', to='authent.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='room_reserved',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_schedules', to='rooms.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
