# Generated by Django 5.2.5 on 2025-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0006_alter_schedules_created_by_alter_schedules_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
